### ISSUE TITLE
Update to Laravel 5.6

### ISSUE THREAD

**Issue by luizjr** [sumityadavbadli/react-laravel-with-jwt-auth#4]
Are you going to upgrade to Laravel 5.6?

**Comment by devinsays** [comment]
@luizjrdeveloper Submitted a pull request with Laravel 5.6 and updated dependencies: https://github.com/sumityadavbadli/react-laravel-with-jwt-auth/pull/8. Let me know if it works for you.

**Comment by sumityadavbadli** [comment]
Updated to Laravel 5.6 with react 16. Pull request #8 merged , Thanks @devinsays
