### ISSUE TITLE
app.js:23404 POST http://localhost:8000/api/auth/register 500 (Internal Server Error)

### ISSUE THREAD

**Issue by ivelinmitev** [sumityadavbadli/react-laravel-with-jwt-auth#5]
Hi when i try to register new user i have this error, can you help me please? But when i put the user in DB and try to login everything is OK, but i have a problem with registration.

**Comment by sumityadavbadli** [comment]
Hi ! 
Will you please provide little more info about the issue.
- Laravel version
- Have you updated any package, if yes then please list them.

As of now, let me share the register controller logic with you.
- It validates name, email, password.
- It HASH the password and merge with the request.
- and then it insert the data into the DB using eloquent's create method (Basically used for mass assignment)

Things you need to check:
- Make sure you have fillable array defined in the user model with all columns you need.
- Check whether you are able to use create method with the user model.
- And also try to dump the registration form data.

For more please check documentation : https://laravel.com/docs/5.6/eloquent#inserting-and-updating-models

And please let me know if any of these things work for you.

**Comment by karadzinov** [comment]
The password_confirmation confirmation does not match.

Always when you try to register.

**Comment by sumityadavbadli** [comment]
Please remove confirm password validation and do the validation manually.

It is because of ree-validate package confirm password functionality not
working.

**Comment by karadzinov** [comment]
Okay another thing. When I'm refreshing the page I'm getting this: Signed in as null.

**Comment by amit131** [comment]
It seems user state lost on page refresh that's why null as const user object is defined as null. I do see that redux persist middleware is in place but something is not correct. Any idea?

**Comment by takosunil** [comment]
Yes, on page refresh, user object becomes null. How to fix this issue?

**Comment by om1** [comment]
Having the same issue.

**Comment by sumityadavbadli** [comment]
As ree-validate package's password confirmation was not working. So, in order fix that i have added the manual function to do the password confirmation.

and i have also fixed user object becomes null issue.

**Comment by mahtias** [comment]
help me by  code, but i don't for fund of solution

**Comment by MdIbrahimBashar11** [comment]
dsfgdsgf
