### ISSUE TITLE
Problems upgrading to reactJS 16

### ISSUE THREAD

**Issue by hopewise** [sumityadavbadli/react-laravel-with-jwt-auth#7]
I know this is not related directly to this repo, however, I thought I can ask here this question as someone else will need an answer too when starting with this repo.

Kindly check my question here: https://stackoverflow.com/questions/49922928/uncaught-typeerror-cannot-read-property-bool-of-undefined-after-upgrade-react
Or try to use reactJS version 16 to see the issue..

**Comment by devinsays** [comment]
@hopewise I updated this project to React 16. See pull: https://github.com/sumityadavbadli/react-laravel-with-jwt-auth/pull/8. I don't remember seeing that issue, but I upgraded a bunch of the dependencies all at once so perhaps I jumped over it.

**Comment by hopewise** [comment]
@devinsays thanks, I've already overcome this problem, can't remember what was the issue.. thanks
